bg_img_link: "soccer_field.jpg"
image:
  avatar:
    size: 50
  soccer_field:
    size: 100
  type: ["image/jpeg", "image/gif", "image/png"]
  size: 5
  resize_to_limit: [500, 500]
  resize_to_limit_preview: [200, 100]
  accept_path: "image/jpeg, image/gif, image/png"
pagy:
  soccer_fields: 10
regex:
  email_regex: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
valid:
  name_max_len: 50
  email_max_len: 255
  password_min_len: 6
  password_max_len: 20
soccer_field:
  rate_range: [1..5]
  rate_step: 0.5
  rate_default: 3
  price_range: [200000..400000]
  price_step: 10000
  price_default: 200000
  field_type: [5, 7, 9, 11]
soccer_field_order:
  day_min: 1
  day_step: 1
  hour_min: 0
  hour_max: 23
  hour_step: 1
  minute_min: 0
  minute_max: 59
  minute_step: 15
  minute_default: 0
  rent_time_min: 1
  rent_time_max: 4
  rent_time_step: 1
  rent_time_default: 1


validates:
  soccer_field:
    name_max_length: 50
    address_max_length: 150
